export {
  ELECTION_TYPE_LABELS,
  ELECTION_STATUS_LABELS,
  ELECTION_STATUS_COLORS,
  REGION_TYPE_LABELS,
  VERIFICATION_STATUS_LABELS,
  VERIFICATION_STATUS_COLORS,
  PREDICTION_STATUS_LABELS,
  CHART_COLORS,
} from "./election";

export {
  APP_NAME,
  APP_DESCRIPTION,
  APP_URL,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  MAIN_NAV,
  QUERY_KEYS,
} from "./app";

export type { NavItem } from "./app";
